export const PACKAGE_NAME = '@kanbots/api';

export {
  createSupervisor,
  RateLimitedError,
  type AgentSupervisor,
  type CooldownListener,
  type CooldownState,
  type CreateSupervisorOptions,
  type ResumeRunInput,
  type StartRunInput,
} from './agent-runs/supervisor.js';
export {
  createAutopilotManager,
  type AutopilotManager,
  type AutopilotManagerOpts,
  type AutopilotRepoConfig,
  type StartAutopilotInput,
  type StartAutopilotResult,
} from './autopilot/orchestrator.js';
export {
  reconcileIssueLabels,
  type ReconcileLabelsResult,
} from './workspace-reconcile.js';
export {
  bootstrapWorkspace,
  type WorkspaceBootstrapResult,
} from './workspace-bootstrap.js';

export {
  startToolBridge,
  type ToolBridge,
  type ToolDispatcher,
} from './tool-bridge.js';
export { dispatchChatTool } from './chat-tools-dispatch.js';

export {
  createCurator,
  CuratorError,
  CURATOR_JSON_SCHEMA,
  CURATOR_SYSTEM_PROMPT,
  renderCuratorPrompt,
  type CreateCuratorOptions,
  type CuratorOutcome,
  type CuratorSpawnFn,
} from './curator/index.js';

export {
  createChatHandlers,
  createHandlers,
  createProvidersHandlers,
  type ChatHandlerDeps,
  type ChatHandlers,
  type ChatToolRuntime,
  type CreateHandlersOptions,
  type HandlerDeps,
  type Handlers,
  type ProvidersHandlerDeps,
  type ProvidersHandlers,
  type ProvidersRuntime,
  type SentryAnalyzerFn,
  type SentryRuntime,
  type SubscriptionRegistry,
} from './handlers/index.js';
export type {
  AgentCheck,
  AgentEvent,
  AgentEventType,
  AgentKey,
  AgentRun,
  AgentRunEventPayload,
  AgentRunStatus,
  AutopilotCheckCommand,
  AutopilotChildEntry,
  AutopilotChildKind,
  AutopilotChildStatus,
  AutopilotConfig,
  AutopilotEffort,
  AutopilotKind,
  AutopilotPersonaSnapshot,
  AutopilotPlanningEvent,
  AutopilotPlanningSlot,
  AutopilotSession,
  AutopilotStatus,
  BridgeChannels,
  Card,
  CardStatus,
  CardTemplatePayload,
  CardType,
  ChannelArgs,
  ChannelName,
  ChannelResult,
  ChatConversation,
  ChatPayload,
  ChatPostMessageResult,
  ChatSessionPayload,
  ChatSessionStatus,
  CheckKind,
  Comment,
  Config,
  CooldownStatePayload,
  CostBreakdownItem,
  CostTimeSeriesPoint,
  FrontierPoint,
  PersonaModelRollupRow,
  CreateIssueInput,
  DecisionPayload,
  DecoratedIssue,
  DiffFile,
  DiffFileStatus,
  DiffPayload,
  DispatchResult,
  DraftedIssue,
  DraftedPrDescription,
  DraftIssueFn,
  DraftIssueInput,
  DraftPrDescriptionFn,
  SuggestFeatureBacklogEntry,
  SuggestFeatureEntryStatus,
  SuggestFeatureFn,
  SuggestFeatureInput,
  EventSubscribeResult,
  ForkRunResult,
  Issue,
  IssueActiveRunPayload,
  IssueDetail,
  IssueRelationPayload,
  Message,
  PendingDecisionPayload,
  PlannerEvent,
  PostMessageResult,
  PrCommentPayload,
  PrCommentsListResult,
  PreviewState,
  PreviewStatePayload,
  RecentActivityKind,
  RecentActivityPayload,
  ProviderConfigPayload,
  ProviderId,
  ProviderSaveInput,
  ProviderSettingsInput,
  ProviderSettingsPayload,
  ProviderTestConnectionResult,
  ProvidersPayload,
  ResolveCardResult,
  ReviewCommentPayload,
  Role,
  RunStatsResult,
  SentryAnalyzerInput,
  SentryConfigInput,
  SentryConfigPayload,
  SentryImportStatus,
  SentryMetaPayload,
  SentrySuggestion,
  SentrySuggestionCategory,
  SentrySuggestionConfidence,
  SentrySuggestionVerdict,
  SentrySyncResult,
  SentryTestConnectionResult,
  ShipCommitResult,
  ShipMergeResult,
  ShipPRResult,
  ShipStatus,
  SlashCommandPayload,
  SplitResult,
  StatusKey,
  ThreadPayload,
  UpdateIssuePatch,
  UploadAttachmentResult,
  Workspace,
  WorkspaceAcpCommandBridgePayload,
  WorkspaceBudgets,
  WorkspaceFolderPayload,
  WorkspaceHouseRules,
  WorkspaceRepoPayload,
  WorkspaceRepoStatus,
  WorkspaceRunScriptResult,
  WorkspaceScriptsBridgePayload,
} from './bridge.js';
