import { execFile } from 'node:child_process';
import { chmod, mkdir, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { promisify } from 'node:util';
import type { IssueRef } from '@kanbots/core';

const execFileAsync = promisify(execFile);

export interface StampWorktreeIdentityInput {
  worktreePath: string;
  runId: number;
  issueNumber: IssueRef;
}

export interface StampWorktreeIdentityResult {
  userName: string;
  userEmail: string;
  hookInstalled: boolean;
  hookSkippedReason: string | null;
}

const TRAILER_RUN_ID = 'Kodra-Run-Id';
const TRAILER_ISSUE = 'Kodra-Issue';

/**
 * Stamp a freshly-created worktree with a per-run git identity and install a
 * commit-msg hook that appends Kodra-Run-Id / Kodra-Issue trailers to
 * every commit made inside it. Identity and hooksPath are written via
 * `git config --worktree` so they don't leak into the parent repo's config.
 */
export async function stampWorktreeIdentity(
  input: StampWorktreeIdentityInput,
): Promise<StampWorktreeIdentityResult> {
  const { worktreePath, runId, issueNumber } = input;
  const userName = `kodra agent (run #${runId})`;
  const userEmail = `agent+${runId}@kodra.local`;

  // Per-worktree config requires extensions.worktreeConfig=true on the
  // common repo. Setting this is idempotent and recognised by all current
  // git versions; older clients ignore the extension. Without it,
  // `git config --worktree` falls back to common config and would pollute
  // the parent repo's user.name / user.email.
  await git(worktreePath, ['config', '--local', 'extensions.worktreeConfig', 'true']);

  await git(worktreePath, ['config', '--worktree', 'user.name', userName]);
  await git(worktreePath, ['config', '--worktree', 'user.email', userEmail]);

  const externalHooksPath = await detectExternalHooksPath(worktreePath);
  if (externalHooksPath !== null) {
    return {
      userName,
      userEmail,
      hookInstalled: false,
      hookSkippedReason: `core.hooksPath already set to ${externalHooksPath}`,
    };
  }

  const gitDir = (await git(worktreePath, ['rev-parse', '--git-dir'])).trim();
  // For linked worktrees `--git-dir` returns the per-worktree gitdir, which
  // is private to this worktree (lives under <common>/.git/worktrees/<name>).
  // Hooks placed there are not auto-discovered by git, but pointing
  // core.hooksPath at it gives us a private hook directory that won't show
  // up as an untracked file inside the worktree itself.
  // Git resolves a relative core.hooksPath against the git directory, so an
  // already-relative `git rev-parse --git-dir` result would otherwise become
  // `.git/.git/kodra-hooks` and silently skip the hook.
  const hooksDir = resolve(worktreePath, gitDir, 'kodra-hooks');
  await mkdir(hooksDir, { recursive: true });

  const hookPath = join(hooksDir, 'commit-msg');
  await writeFile(hookPath, renderCommitMsgHook({ runId, issueNumber }), 'utf8');
  await chmod(hookPath, 0o755);

  await git(worktreePath, ['config', '--worktree', 'core.hooksPath', hooksDir]);

  return {
    userName,
    userEmail,
    hookInstalled: true,
    hookSkippedReason: null,
  };
}

async function detectExternalHooksPath(cwd: string): Promise<string | null> {
  try {
    const out = await git(cwd, ['config', '--show-origin', '--get', 'core.hooksPath']);
    const line = out.trim();
    if (line.length === 0) return null;
    // `--show-origin` prefixes "<origin>\t" before the value.
    const tabIdx = line.indexOf('\t');
    return tabIdx >= 0 ? line.slice(tabIdx + 1) : line;
  } catch (err) {
    if (isMissingConfigError(err)) return null;
    throw err;
  }
}

function isMissingConfigError(err: unknown): boolean {
  // `git config --get` exits 1 when the key is unset.
  return (
    typeof err === 'object' &&
    err !== null &&
    'code' in err &&
    (err as { code?: number }).code === 1
  );
}

async function git(cwd: string, args: string[]): Promise<string> {
  const { stdout } = await execFileAsync('git', args, { cwd });
  return stdout;
}

function renderCommitMsgHook(opts: { runId: number; issueNumber: IssueRef }): string {
  // POSIX shell: idempotent — skip if Kodra-Run-Id is already present.
  // `git interpret-trailers` keeps the trailer block well-formed and
  // composes with Co-authored-by / Signed-off-by etc.
  return `#!/bin/sh
# Auto-generated by @kanbots/dispatcher. Stamps each commit with the
# kodra run/issue trailers so commit metadata can be joined back to a
# specific agent run.
set -e
msg_file="$1"
if grep -q '^${TRAILER_RUN_ID}:' "$msg_file"; then
  exit 0
fi
git interpret-trailers \\
  --in-place \\
  --if-exists addIfDifferent \\
  --trailer "${TRAILER_RUN_ID}=${opts.runId}" \\
  --trailer "${TRAILER_ISSUE}=${String(opts.issueNumber)}" \\
  "$msg_file"
`;
}
